# Site settings
title: Json Writer
description: >
  <p>Hi there, my name is Jason Loo. I write about Software Engineering.</p>
baseurl: ""
url: "https://nosajool.github.io/"
github_username:  Nosajool
linkedin_public_username: jasonmloo

markdown: kramdown
kramdown:
  input: GFM

collections:
  projects:
    output: true

plugins:
  - jekyll-sitemap

exclude:
  - .jekyll-cache
