# Site settings
title: Jason Loo
email: jmloo@uwaterloo.ca
description: >
  <p>Hi there, I'm a third year Software Engineering Student at the University of Waterloo.</p>
  <p>This blog is used to document interesting things that I run into as well as occasionally rant about the Ottawa Senators and the Washington Capitals.</p>
baseurl: ""
url: "https://jasonloo.co"
twitter_username: Nosajool
github_username:  Nosajool
linkedin_public_username: jasonmloo

markdown: kramdown
kramdown:
  input: GFM

gems:
  - jekyll-sitemap

collections:
  projects:
    output: true
