# Site settings
title: Jason Loo
email: jmloo@uwaterloo.ca
description: >
  <p>Hi there, I'm a third year Software Engineering Student at the University of Waterloo.</p>
  <p>This blog is used to document interesting things that I run into as well as occasionally rant about the Ottawa Senators and the Washington Capitals.</p>
baseurl: ""
url: "http://nosajool.github.io"
twitter_username: J_waterLoo
github_username:  Nosajool

# Build settings
markdown: kramdown
kramdown:
  input: GFM

collections:
  projects:
    output: true
