# Site settings
title: Json Writer
description: >
  <p>Hi there, my name is Jason Loo. I write about Software Engineering and the Internet</p>
baseurl: ""
url: "https://www.jsonwriter.com"

twitter:
  username: json_writer
  card: summary

facebook:
  publisher: https://www.facebook.com/jsonwriter
  admin: https://www.facebook.com/jsonwriter

github_username:  Nosajool
linkedin_public_username: jasonmloo

markdown: kramdown
kramdown:
  input: GFM

collections:
  projects:
    output: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .jekyll-cache
