# Site settings
title: Jason Loo
email: jmloo@uwaterloo.ca
description: >
  Hi there, I'm a Software Engineering Student at the University of Waterloo.
  <br/><br/>
  I just completed my second co-op term as a Software Engineer at Vidyard and will be starting the 2B school term in May.
  <br/><br/>
  When I'm not architecting or implementing a project, I can be found watching hockey, playing Super Smash Brothers, foosball or biking.
baseurl: ""
url: "http://nosajool.github.io"
twitter_username: J_waterLoo
github_username:  Nosajool

# Build settings
markdown: kramdown
kramdown:
  input: GFM

collections:
  projects:
    output: true
